Upgrade python version to 3.10.4
thermondo/threesixty pull request #684
Opened 2022-09-07 14:29 UTC by SebastianKapunkt

The ```deploy to Heroku``` button will use the newest version of the Heroku build pack. The newest version of that build pack requires python 3.10.4

2022-09-08 04:54 UTC, syphar requested changes
thank you for the fix! 

Is there a specific reason why you didn't update to the latest python version? (3.10.7) 

If not I'm happy to merge after changing to the new version

2022-09-08 07:47 UTC, codingjoe commented
@SebastianKapunkt the latest available version on heroku-22 is 3.10.6 (no .7 yet).

Maybe for clarification: The buildpack isn't the issue, but the latest heroku-22 stack, that doesn't run the Python version in the poetry lock.

2022-09-08 07:48 UTC, SebastianKapunkt commented
@syphar the Heroku build pack has by default the python version 3.10.4 activated. That's the reason I choose it.

```
-----> Building on the Heroku-22 stack

-----> Using buildpacks:

       1. https://github.com/moneymeets/python-poetry-buildpack.git

       2. heroku/python

The currently activated Python version 3.10.4 is not supported by the project (3.9.4).

Trying to find and use a compatible version. 
```

2022-09-08 13:11 UTC, syphar commented
@SebastianKapunkt @codingjoe here it looks like `3.10.7` is available: 
https://devcenter.heroku.com/articles/python-support

2022-09-08 13:57 UTC, SebastianKapunkt commented
Yeah, that's what it states, but I tried it and didn't work for me. :/ I don't have that much time the next days, so feel free to try some different python versions :D

2022-09-26 09:15 UTC, SebastianKapunkt commented
@syphar since you upgraded the config, it also solves the issue. Thanks. So I will close the PR :)

2022-09-26 09:15 UTC, closed without merging